In [130]:
import numpy as np
pi = np.pi

Thay đổi 2 điểm này để cài đặt điểm bắt đầu và kết thúc

In [131]:
startP = np.array([[0],[0],[-420]]); #start
endP = np.array([[0],[120],[-420]]); #end point

Thay đổi thử xem có bớt rung ko

In [132]:
#thay doi tham so Af va af co the lam giam do rung
Af = 1/2; 
af = 0.125;

In [133]:
##
T = 1;

Ca = (1+4*af/pow(pi,2))/(af/pi+2/pow(pi,2));

af = (pow(pi,2)-2*Ca)/(Ca*pi-4*Ca);

sample = 35;

In [134]:
##khai báo x và dot
x = 0;
xdot = 0;
x2dot = 0;

PosAndVel = np.zeros((sample+1,6));

In [135]:
def calPosElipe(startP,endP):
	for i in range(sample +1):
		t = i/sample*T
		u = t/T
		if u>=0 and u <= (Af*af):
			x = Ca*af/pi*u-2*Ca*Af*pow(af,2)/pow(pi,2)*np.sin(pi*u/(2*Af*af))
			xdot = Ca * af / pi / T - Ca * af / pi / T * np.cos(pi * t / T / Af / af / 0.2e1)
			#x2dot = Ca / pow(T, 2) / Af * np.sin(pi * t / T / Af / af / 0.2e1) / 0.2e1
		elif u>(Af*af) and u<=Af:
			x = 2*(Ca*Af*(1-2*af))/pow(pi,2)+Ca*af/pi*u-2*Ca*Af*pow((1-af),2)/pow(pi,2)*np.sin(pi*u/(2*Af*(1-af))+(1-2*af)*pi/(2*(1-af)));
			xdot = Ca * af / pi / T - Ca * (1 - af) / pi / T * np.cos(-(pi * t / T / Af / (1 - af)) / 0.2e1 - ((1 - 2 * af) * pi / (2 - 2 * af)));
			#x2dot = -Ca / (pow(T, 2)) / Af * np.sin(-(pi * t / T / Af / (1 - af)) / 0.2e1 - ((1 - 2 * af) * pi / (2 - 2 * af))) / 0.2e1;
		elif u>Af and u<=(1-af*(1-Af)):
			x = 1-2*Ca*(1-Af)*(1-2*af)/pow(pi,2)-Ca*af*(1-u)/pi+2*Ca*(1-Af)*pow((1-af),2)/pow(pi,2)*np.sin(pi*(1-u)/(2*(1-Af)*(1-af))+(1-2*af)*pi/(2*(1-af)));
			xdot = Ca * af / pi / T - 0.2e1 * Ca * (1 - Af) * (1 - af) / pi / T / (2 - 2 * Af) * np.cos((-pi * (1 - t / T) / (2 - 2 * Af) / (1 - af) - (1 - 2 * af) * pi / (2 - 2 * af)));
			#x2dot = 0.2e1 * Ca * (1 - Af) / (pow(T, 2)) / (pow(2 - 2 * Af) ,2) * np.sin((-pi * (1 - t / T) / (2 - 2 * Af) / (1 - af) - (1 - 2 * af) * pi / (2 - 2 * af)));
		elif u > (1-af*(1-Af)) and u <=1:
			x = 1-Ca*af*(1-u)/pi-2*Ca*(1-Af)*pow(af,2)/pow(pi,2)*np.sin(pi*(1-u)/(2*(1-Af)*af));
			xdot = Ca * af / pi / T + 0.2e1 * Ca * (1 - Af) * af / pi / T / (2 - 2 * Af) * np.cos((pi * (1 - t / T) / (2 - 2 * Af) / af));
			#x2dot = 0.2e1 * Ca * (1 - Af) / (pow(T, 2)) / (pow(2 - 2 * Af) , 2) * np.sin((pi * (1 - t / T) / (2 - 2 * Af) / af));
		s0 = (startP+endP)/2;
		
		# phi = np.arctan((startP[1]-endP[1])/(startP[0]-endP[0]))

		if startP[0] != endP[0]:
			phi = np.arctan((startP[1]-endP[1])/(startP[0]-endP[0]))
		else:
			# Xử lý trường hợp startP[0] = endP[0]
			phi = 0  # Hoặc giá trị mong muốn khác tùy theo yêu cầu của bạn

		A = float(1/2*np.sqrt(pow((startP[0]-endP[0]),2)+pow((startP[1]-endP[1]),2)));
		B = 50;
		C = float((startP[2]-endP[2])/2);

		# print(A)
		# print(B)
		# print(C)

		rot = np.array([[np.cos(phi),-np.sin(phi),0], [np.sin(phi) ,np.cos(phi) ,0], [0, 0, 1]]);
		ABC = np.array([[A, 0, 0], [0, 1, 0], [C, 0, B]], dtype=np.float64)

		ss0 = np.array([[np.cos(pi*x)], [0], [np.sin(pi*x)]]);
		ss0dot = np.array([[-xdot*pi*np.sin(pi*x)],[0], [xdot*pi*np.cos(pi*x)]]);
		#ss02dot = np.array([[-x2dot*pi*np.sin(pi*x)-pow(xdot,2)*pi*np.cos(pi*x)], [0], [x2dot*pi*np.cos(pi*x)-pow(xdot,2)*pi*np.sin(pi*x)]]);

		s = s0 + np.dot(np.dot(rot,ABC),ss0)
		PosAndVel[i][0] = s[0];
		PosAndVel[i][1] = s[1];
		PosAndVel[i][2] = s[2];


		sdot = np.dot(np.dot(rot,ABC),ss0dot)
		# print(sdot[2]);
		PosAndVel[i][3] = sdot[0];
		PosAndVel[i][4] = sdot[1];
		PosAndVel[i][5] = sdot[2];

	return PosAndVel;


In [136]:
# # calcutation for PH curve
# m = 10
# r = 10
# j = 40;
# w = 40;
# height = 40;
# u0 = np.sqrt(5*(35*m + r - np.sqrt(m^2 + r^2 + 70*m*r))/34)
# u2 = np.sqrt(5*(m + 35*r - np.sqrt(m^2 + r^2 + 70*m*r))/68)
# l_BC = 1/5*pow(u0,2) + 1/15*u0*u2 + 2/5*pow(u2,2);
# l_All = 2*j + 2*l_BC + w - 2*r;

# def calPosElipe(startP,endP):
#   for i in range(sample +1):
#     t = i/sample*T
#     u = t/T
#     PosAndVel[i][0] = startP[0] + l_All*(6*pow(u,5) - 15*pow(u,4) + 10*pow(u,3))
#     PosAndVel[i][1] = startP[1];
#     PosAndVel[i][2] = startP[2] + height*u;

#     PosAndVel[i][3] = l_All*(30*pow(u,4) - 60*pow(u,3) + 30*pow(u,2))
#     PosAndVel[i][4] = 0;
#     PosAndVel[i][5] = height;
#   return PosAndVel;


In [137]:
PosAndVel = calPosElipe(startP,endP);
print(PosAndVel);

[[  59.97026739   60.         -418.42611843   -1.40831167    0.
    37.2649225 ]
 [  59.89948337   60.         -417.1070138    -3.82288863    0.
    54.96748526]
 [  59.73343076   60.         -415.29205385   -8.16478183    0.
    71.93960766]
 [  59.41001766   60.         -413.00546834  -14.90792605    0.
    87.93378741]
 [  58.85525389   60.         -410.27963588  -24.40730813    0.
   102.62663653]
 [  57.9869949    60.         -407.1572431   -36.8746456     0.
   115.62126155]
 [  56.71938115   60.         -403.69322308  -52.35446346    0.
   126.46040687]
 [  54.96792009   60.         -399.95616329  -70.7036104     0.
   134.65036879]
 [  52.65506085   60.         -396.0288865   -91.57788497    0.
   139.69473169]
 [  49.71600408   60.         -392.0079508  -114.42957297    0.
   141.13583834]
 [  46.10438549   60.         -388.001892   -138.51921565    0.
   138.60071467]
 [  41.79739227   60.         -384.12814087 -162.94379179    0.
   131.84711401]
 [  36.79983176   60.       

C:\Users\lpnam\AppData\Local\Temp\ipykernel_20792\1888277816.py:31: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  A = float(1/2*np.sqrt(pow((startP[0]-endP[0]),2)+pow((startP[1]-endP[1]),2)));
C:\Users\lpnam\AppData\Local\Temp\ipykernel_20792\1888277816.py:33: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  C = float((startP[2]-endP[2])/2);
C:\Users\lpnam\AppData\Local\Temp\ipykernel_20792\1888277816.py:47: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  PosAndVel[i][0

In [138]:
ABC = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]);
ss0 = np.array([[1],[2],[3]]);
CDE = np.array([[2, 3, 4], [4, 5, 6], [7, 8, 9]]);
print(np.dot(np.dot(ABC,CDE),ss0)+ss0)

[[235]
 [542]
 [849]]


In [139]:
import math
R = 120
r = 38
l = 425
L =  193.5

In [140]:
def FKinem(theta1, theta2, theta3):
    pos = np.zeros(3)
    t = R-r;
    theta1 = np.deg2rad(theta1);
    theta2 = np.deg2rad(theta2);
    theta3 = np.deg2rad(theta3);

    y1 = -(t + L*math.cos(theta1));
    z1 = - L * math.sin(theta1);

    y2 = (t + L*math.cos(theta2)) * math.sin(pi/6);
    x2 = y2 * math.tan(pi/3);
    z2 = -L * math.sin(theta2);

    y3 = (t + L*math.cos(theta3)) * math.sin(pi/6);
    x3 = -y3 * math.tan(pi/3);
    z3 = -L * math.sin(theta3);

    w1 = pow(y1,2) + pow(z1,2);
    w2 = pow(x2,2) + pow(y2,2) + pow(z2,2);
    w3 = pow(x3,2) + pow(y3,2) + pow(z3,2)

    dnm = (y2-y1)*x3 - (y3-y1)*x2;

    a1 = (z2-z1)*(y3-y1) - (z3-z1)*(y2-y1);
    b1= -( (w2-w1)*(y3-y1) - (w3-w1)*(y2-y1) ) / 2;

    a2 = -(z2-z1)*x3 + (z3-z1)*x2;
    b2 = ( (w2-w1)*x3 - (w3-w1)*x2) / 2;

    a = pow(a1,2) + pow(a2,2) + pow(dnm,2);
    b = 2 * (a1*b1 + a2*(b2 - y1*dnm) - z1*pow(dnm,2));
    c = (b2 - y1*dnm)*(b2 - y1*dnm) + b1*b1 + pow(dnm,2)*(pow(z1,2) - l*l)

    d = b*b - 4*a*c;
    if d >= 0:
        Z = -0.5*(b + math.sqrt(d)) / a;
        X = (a1*Z + b1) / dnm;
        Y = (a2*Z + b2) / dnm;
        if (abs(X) > 300 or abs(Y) > 300 or  Z > 0 or Z < -500):
            fl = -1;
        else:
            fl = 0;

    else:
        X = None;
        Y = None;
        Z = None;
        fl = -1;

    pos[0] = X
    pos[1] = Y
    pos[2] = Z
    return pos

In [141]:
def IKinemTh(x0, y0, z0):
    theta = 0
    y1 = -R;
    y0 = y0-r;

    a = (pow(x0,2) + pow(y0,2) + pow(z0,2) + pow(L,2) - pow(l,2) - pow(y1,2))/(2*z0);
    b = (y1-y0)/z0;

    D = -pow((a + b*y1),2) + pow(L,2)*(pow(b,2)+1);
    if D < 0:
        theta = None;
    else:
        yj = (y1 - a*b - math.sqrt(D)) / (pow(b,2) + 1);
        zj = a + b*yj;
        theta = math.atan(-zj/(y1-yj));
        if (yj>y1):
            theta = theta + np.pi;
        theta = np.rad2deg(theta);
    return theta

def IKinem(X, Y, Z):
    theta = np.zeros(3)
    x0 = X;
    y0 = Y;
    z0 = Z;
    theta1 = IKinemTh(x0,y0,z0);

    x0 = X*math.cos(2*pi/3) + Y*math.sin(2*pi/3);
    y0 = Y*math.cos(2*pi/3) - X*math.sin(2*pi/3);
    z0 =Z;
    theta2 = IKinemTh(x0,y0,z0);
    x0 = X*math.cos(2*pi/3) - Y*math.sin(2*pi/3);


    y0 =Y*math.cos(2*pi/3) + X*math.sin(2*pi/3);
    z0 = Z;
    theta3 = IKinemTh(x0,y0,z0);
    fl=0
    if (theta1 != None and theta1 != None and theta1 != None):
        fl = 0;
    else:
        fl = -1;
    theta[0]= theta1
    theta[1] = theta2
    theta[2] = theta3
    # theta[3] = fl
    return theta

In [142]:
print(IKinem(100,0,-450))

[35.76743965 20.21165645 49.56879952]


In [143]:
# theta1dot = 0;
# theta2dot = 0;
# theta3dot = 0;

def CalThetaDot(q1,q2,q3,x,y,z,Xdot, Ydot, Zdot):

    wB = R;
    uB = 2*R;
    sB = np.sqrt(3)*uB;
    wP = r/2;
    uP = r;
    sP = np.sqrt(3)*uP;

    q1 = pi/180 *q1;
    q2 = pi/180 *q2;
    q3 = pi/180 *q3;

    a = wB - uP;
    b = sP/2-np.sqrt(3)/2*wB;
    c = wP - 1/2*wB;

    JX = np.zeros((3,3));
    JX[0,0] = x;
    JX[0,1] = y + a + L*np.cos(q1);
    JX[0,2] = z + L*np.sin(q1);

    JX[1,0] = 2*(x+b)-np.sqrt(3)*L*np.cos(q2);
    JX[1,1]= 2*(y+c) - L*np.cos(q2);
    JX[1,2] =2*(z+L*np.sin(q2));

    JX[2,0] = 2*(x-b)+np.sqrt(3)*L*np.cos(q3);
    JX[2,1] = 2*(y+c) - L*np.cos(q3);
    JX[2,2] = 2*(z+L*np.sin(q3));

    Jphi = np.zeros((3,3));
    Jphi[0,0] = L*((y+a)*np.sin(q1)-z*np.cos(q1));
    Jphi[1,1] = -L*((np.sqrt(3)*(x+b)+y+c)*np.sin(q2)+2*z*np.cos(q2));
    Jphi[2,2] = L*((np.sqrt(3)*(x-b)-y-c)*np.sin(q3)-2*z*np.cos(q3));

    Xd = np.array([[Xdot],[Ydot],[Zdot]]);
    theta1Dot = np.zeros(3);
    thetaDot = np.dot(np.dot(JX,np.linalg.inv(Jphi)),Xd);
    theta1Dot[0] = thetaDot[0]
    theta1Dot[1] = thetaDot[1]
    theta1Dot[2] = thetaDot[2]
    return theta1Dot;

In [144]:
tmp = CalThetaDot(38.43,22.78,52.23,-100,0,-450,0,0,74.53)
print(tmp)

[-0.2334714  -0.53116417 -0.42065532]


C:\Users\lpnam\AppData\Local\Temp\ipykernel_20792\3591904314.py:43: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  theta1Dot[0] = thetaDot[0]
C:\Users\lpnam\AppData\Local\Temp\ipykernel_20792\3591904314.py:44: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  theta1Dot[1] = thetaDot[1]
C:\Users\lpnam\AppData\Local\Temp\ipykernel_20792\3591904314.py:45: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  theta1Dot[2] = thetaDot[2]


In [145]:
A = np.array([[ 1, 1, 3],[ -2, 5, 1],[ 1, 9, 7]])
inv_ABC = np.linalg.inv(A)
print(inv_ABC)

[[-0.92857143 -0.71428571  0.5       ]
 [-0.53571429 -0.14285714  0.25      ]
 [ 0.82142857  0.28571429 -0.25      ]]


In [146]:
def calVelSignal(startP,endP):
	XAndDX = calPosElipe(startP,endP);

	qAndDq = np.zeros((sample+1,6));
	# dq = np.zeros((sample+1,3));
	for i in range(sample +1):
		qAndDq[i][0:3] = IKinem(XAndDX[i][0],XAndDX[i][1],XAndDX[i][2]);
		qAndDq[i][3:6] = CalThetaDot(qAndDq[i][0],qAndDq[i][1],qAndDq[i][2],XAndDX[i,0],XAndDX[i][1],XAndDX[i][2],XAndDX[i][3], XAndDX[i][4], XAndDX[i][5]);
	return qAndDq;

In [147]:
XAndDX = calPosElipe(startP,endP);
print(XAndDX[0,5])

37.26492250195509


C:\Users\lpnam\AppData\Local\Temp\ipykernel_20792\1888277816.py:31: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  A = float(1/2*np.sqrt(pow((startP[0]-endP[0]),2)+pow((startP[1]-endP[1]),2)));
C:\Users\lpnam\AppData\Local\Temp\ipykernel_20792\1888277816.py:33: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  C = float((startP[2]-endP[2])/2);
C:\Users\lpnam\AppData\Local\Temp\ipykernel_20792\1888277816.py:47: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  PosAndVel[i][0

In [148]:
signal = calVelSignal(startP,endP);
print(signal);

[[ 3.77403451e+01  1.15437494e+01  3.11771414e+01 -7.11913948e-02
  -1.71468656e-01 -1.58394364e-01]
 [ 3.74570387e+01  1.11907047e+01  3.08613194e+01 -1.06227957e-01
  -2.45510905e-01 -2.45515224e-01]
 [ 3.70647931e+01  1.07128567e+01  3.04131422e+01 -1.41240209e-01
  -3.07804173e-01 -3.43004288e-01]
 [ 3.65665212e+01  1.01241505e+01  2.98255192e+01 -1.76092265e-01
  -3.54969102e-01 -4.53393380e-01]
 [ 3.59664268e+01  9.44243696e+00  2.90904149e+01 -2.10393420e-01
  -3.83602579e-01 -5.78223825e-01]
 [ 3.52706480e+01  8.68987210e+00  2.81999238e+01 -2.43452937e-01
  -3.90325084e-01 -7.17829978e-01]
 [ 3.44879412e+01  7.89325478e+00  2.71475088e+01 -2.74248486e-01
  -3.71882245e-01 -8.71118252e-01]
 [ 3.36303466e+01  7.08420719e+00  2.59293827e+01 -3.01417886e-01
  -3.25308302e-01 -1.03536404e+00]
 [ 3.27137659e+01  6.29908285e+00  2.45459979e+01 -3.23286138e-01
  -2.48158763e-01 -1.20606135e+00]
 [ 3.17583609e+01  5.57847270e+00  2.30035819e+01 -3.37940530e-01
  -1.38816719e-01 -1.3768

C:\Users\lpnam\AppData\Local\Temp\ipykernel_20792\1888277816.py:31: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  A = float(1/2*np.sqrt(pow((startP[0]-endP[0]),2)+pow((startP[1]-endP[1]),2)));
C:\Users\lpnam\AppData\Local\Temp\ipykernel_20792\1888277816.py:33: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  C = float((startP[2]-endP[2])/2);
C:\Users\lpnam\AppData\Local\Temp\ipykernel_20792\1888277816.py:47: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  PosAndVel[i][0

In [149]:
stepNum = np.zeros((sample +1,3));
velNum = np.zeros((sample,3));

for i in range(sample+1):
  stepNum[i] = signal[i][0:3];
print(stepNum)

[[37.74034512 11.54374941 31.17714135]
 [37.45703872 11.19070475 30.8613194 ]
 [37.06479312 10.71285672 30.41314219]
 [36.56652125 10.12415046 29.82551919]
 [35.96642679  9.44243696 29.09041488]
 [35.27064805  8.6898721  28.19992382]
 [34.48794122  7.89325478 27.14750884]
 [33.63034664  7.08420719 25.92938274]
 [32.71376591  6.29908285 24.54599793]
 [31.75836092  5.5784727  23.00358195]
 [30.78867047  4.96617221 21.3156173 ]
 [29.83333272  4.50748721 19.50410991]
 [28.92431053  4.2468076  17.60042832]
 [28.09555202  4.22448635 15.64544043]
 [27.38108901  4.47323023 13.68865671]
 [26.81268058  5.01441967 11.78614647]
 [26.41723353  5.8549655   9.99716123]
 [26.21434204  6.98538742  8.37967607]
 [26.21434204  8.37967607  6.98538742]
 [26.41723353  9.99716123  5.8549655 ]
 [26.81268058 11.78614647  5.01441967]
 [27.38108901 13.68865671  4.47323023]
 [28.09555202 15.64544043  4.22448635]
 [28.92431053 17.60042832  4.2468076 ]
 [29.83333272 19.50410991  4.50748721]
 [30.78867047 21.3156173 

In [150]:
# check quỹ đạo để đảo ngược thứ tự step truyền vào
check_direction =  FKinem(stepNum[0][0], stepNum[0][1], stepNum[0][2]) - np.transpose(endP)
if np.sum(np.abs(check_direction)) <= 10:
  print("true")

In [151]:
np.transpose(startP)

array([[   0,    0, -420]])

In [152]:
for i in range(sample):
  velNum[i] = signal[i+1][3:6];
print(velNum);

[[-0.10622796 -0.2455109  -0.24551522]
 [-0.14124021 -0.30780417 -0.34300429]
 [-0.17609227 -0.3549691  -0.45339338]
 [-0.21039342 -0.38360258 -0.57822383]
 [-0.24345294 -0.39032508 -0.71782998]
 [-0.27424849 -0.37188225 -0.87111825]
 [-0.30141789 -0.3253083  -1.03536404]
 [-0.32328614 -0.24815876 -1.20606135]
 [-0.33794053 -0.13881672 -1.37687305]
 [-0.34336462  0.00313058 -1.5397411 ]
 [-0.33763577  0.17646393 -1.68522096]
 [-0.31917992  0.37789825 -1.80309391]
 [-0.28706069  0.6017226  -1.88327705]
 [-0.24126103  0.83963071 -1.91698387]
 [-0.18289794  1.08087886 -1.89799558]
 [-0.11430443  1.31288701 -1.82380836]
 [-0.03892537  1.52231722 -1.69637013]
 [ 0.03898951  1.69652421 -1.52216104]
 [ 0.11485864  1.82512111 -1.31152034]
 [ 0.18431818  1.90131195 -1.07733719]
 [ 0.24373134  1.92267203 -0.83341133]
 [ 0.2905519   1.8912098  -0.59286428]
 [ 0.32348273  1.81275158 -0.36691546]
 [ 0.34242852  1.6958606  -0.16417941]
 [ 0.34829063  1.550572    0.0095274 ]
 [ 0.34267414  1.38719603

In [153]:
calStepNum = np.zeros((sample,3));
calVelNum = np.zeros((sample,3));
Tiso = 36/20;
vibuoc = 16;

# calStepNum[0][0] = int((stepNum[0][0]-0)/(360 / 800 / vibuoc) *Tiso);
# calStepNum[0][1] = int((stepNum[0][1]-0)/(360 / 800 / vibuoc) *Tiso);
# calStepNum[0][2] = int((stepNum[0][2]-0)/(360 / 800 / vibuoc) *Tiso);

for i in range(sample):
  calStepNum[i][0] = int((stepNum[i+1][0] - stepNum[i][0])/(360 / 800 / vibuoc) *Tiso);
  calStepNum[i][1] = int((stepNum[i+1][1] - stepNum[i][1])/(360 / 800 / vibuoc) *Tiso);
  calStepNum[i][2] = int((stepNum[i+1][2] - stepNum[i][2])/(360 / 800 / vibuoc) *Tiso);
  if calStepNum[i][0] == 0:
    calStepNum[i][0] = 1;
  if calStepNum[i][1] == 0:
    calStepNum[i][1] = 1;
  if calStepNum[i][2] == 0:
    calStepNum[i][2] = 1;

# calStepNum[sample][0] = -calStepNum[sample-1][0]
# calStepNum[sample][1] = -calStepNum[sample-1][1]
# calStepNum[sample][2] = -calStepNum[sample-1][2]

# calStepNum[sample-1][0] = calStepNum[sample-1][0]*2
# calStepNum[sample-1][1] = calStepNum[sample-1][1]*2
# calStepNum[sample-1][2] = calStepNum[sample-1][2]*2

# calStepNum[sample][0] = calStepNum[sample][0] - calStepNum[sample-1][0]
# calStepNum[sample][1] = calStepNum[sample][1] - calStepNum[sample-1][1]
# calStepNum[sample][2] = calStepNum[sample][2] - calStepNum[sample-1][2]

# calStepNum= np.round(calStepNum.transpose()).astype(int)
print(calStepNum)

hesoTest = 1
for i in range(sample-1):
  calVelNum[i][0] = int(abs(velNum[i][0])*(sample+1));
  calVelNum[i][1] = int(abs(velNum[i][1])*(sample+1));
  calVelNum[i][2] = int(abs(velNum[i][2])*(sample+1));

for i in range(sample-1):
  if (calVelNum[i+1][0] - calVelNum[i][0]) > 3:
    calVelNum[i+1][0] = calVelNum[i][0] + 3;

  if (calVelNum[i+1][1] - calVelNum[i][1]) > 3:
    calVelNum[i+1][1] = calVelNum[i][1] + 3;

  if (calVelNum[i+1][2] - calVelNum[i][2]) > 3:
    calVelNum[i+1][2] = calVelNum[i][2] + 3;

  if calVelNum[i+1][0] >= 20:
    calVelNum[i+1][0] = 20
  if calVelNum[i+1][1] >= 20:
    calVelNum[i+1][1] = 20
  if calVelNum[i+1][2] >= 20:
    calVelNum[i+1][2] = 20

  # if calVelNum[i][0] - calVelNum[i+1][0] > 2:
  #   calVelNum[i][0] = calVelNum[i+1][0] + 2;
  # if calVelNum[i][1] - calVelNum[i+1][1] > 2:
  #   calVelNum[i][1] = calVelNum[i][1] + 2;
  # if calVelNum[i][2] - calVelNum[i][2] > 2:
  #   calVelNum[i][2] = calVelNum[i][2] + 2;

  if calVelNum[i][0] == 0:
    calVelNum[i][0] = 1;
  if calVelNum[i][1] == 0:
    calVelNum[i][1] = 1;
  if calVelNum[i][2] == 0:
    calVelNum[i][2] = 1;

calVelNum[sample-1][0] = calVelNum[sample-2][0] - 2
calVelNum[sample-1][1] = calVelNum[sample-2][1] - 2
calVelNum[sample-1][2] = calVelNum[sample-2][2] - 2

# calVelNum[sample-1][0] = calVelNum[sample-2][0]*0.75
# calVelNum[sample-1][1] = calVelNum[sample-2][1]*0.75
# calVelNum[sample-1][2] = calVelNum[sample-2][2]*0.75

print(calVelNum);

[[ -18.  -22.  -20.]
 [ -25.  -30.  -28.]
 [ -31.  -37.  -37.]
 [ -38.  -43.  -47.]
 [ -44.  -48.  -56.]
 [ -50.  -50.  -67.]
 [ -54.  -51.  -77.]
 [ -58.  -50.  -88.]
 [ -61.  -46.  -98.]
 [ -62.  -39. -108.]
 [ -61.  -29. -115.]
 [ -58.  -16. -121.]
 [ -53.   -1. -125.]
 [ -45.   15. -125.]
 [ -36.   34. -121.]
 [ -25.   53. -114.]
 [ -12.   72. -103.]
 [   1.   89.  -89.]
 [  12.  103.  -72.]
 [  25.  114.  -53.]
 [  36.  121.  -34.]
 [  45.  125.  -15.]
 [  53.  125.    1.]
 [  58.  121.   16.]
 [  61.  115.   29.]
 [  62.  108.   39.]
 [  61.   98.   46.]
 [  58.   88.   50.]
 [  54.   77.   51.]
 [  50.   67.   50.]
 [  44.   56.   48.]
 [  38.   47.   43.]
 [  31.   37.   37.]
 [  25.   28.   30.]
 [  18.   20.   22.]]
[[ 3.  8.  8.]
 [ 5. 11. 11.]
 [ 6. 12. 14.]
 [ 7. 13. 17.]
 [ 8. 14. 20.]
 [ 9. 13. 20.]
 [10. 11. 20.]
 [11.  8. 20.]
 [12.  4. 20.]
 [12.  1. 20.]
 [12.  3. 20.]
 [11.  6. 20.]
 [10.  9. 20.]
 [ 8. 12. 20.]
 [ 6. 15. 20.]
 [ 4. 18. 20.]
 [ 1. 20. 20.]
 [ 1. 20.

In [154]:
# check quỹ đạo để đảo ngược thứ tự step truyền vào
check_direction =  FKinem(stepNum[0][0], stepNum[0][1], stepNum[0][2]) - np.transpose(startP)
# if np.sum(np.abs(check_direction)) >= 10:
#   print("quy dao bi nguoc")
#   calStepNum = np.flip(calStepNum)

flat_arr = np.reshape(calStepNum, -1, order='F')
flat_arr= np.round(flat_arr.transpose()).astype(int)
# flat_arr= np.round(flat_arr.transpose()).astype(int)
listToStr_step = ','.join([str(elem) for elem in flat_arr])
print(listToStr_step)

-18,-25,-31,-38,-44,-50,-54,-58,-61,-62,-61,-58,-53,-45,-36,-25,-12,1,12,25,36,45,53,58,61,62,61,58,54,50,44,38,31,25,18,-22,-30,-37,-43,-48,-50,-51,-50,-46,-39,-29,-16,-1,15,34,53,72,89,103,114,121,125,125,121,115,108,98,88,77,67,56,47,37,28,20,-20,-28,-37,-47,-56,-67,-77,-88,-98,-108,-115,-121,-125,-125,-121,-114,-103,-89,-72,-53,-34,-15,1,16,29,39,46,50,51,50,48,43,37,30,22


Copy đoạn kết quả sau, cho vào mảng int data[numberStepper * 2 * numberSplit] = {kết quả}; trong arduino

In [155]:
# arrStep = np.zeros(sample*3)
# arrStep = calStepNum.flatten()

# arrVel = calVelNum.flatten()

# động cơ và vận tốc
arrStep = np.reshape(calStepNum, -1, order='F')
arrVel = np.reshape(calVelNum, -1, order='F')

arrStepVel = np.concatenate((arrStep,arrVel),axis=None)

arrStepVel= np.round(arrStepVel.transpose()).astype(int)

listToStr = ','.join([str(elem) for elem in arrStepVel])
print(listToStr);

-18,-25,-31,-38,-44,-50,-54,-58,-61,-62,-61,-58,-53,-45,-36,-25,-12,1,12,25,36,45,53,58,61,62,61,58,54,50,44,38,31,25,18,-22,-30,-37,-43,-48,-50,-51,-50,-46,-39,-29,-16,-1,15,34,53,72,89,103,114,121,125,125,121,115,108,98,88,77,67,56,47,37,28,20,-20,-28,-37,-47,-56,-67,-77,-88,-98,-108,-115,-121,-125,-125,-121,-114,-103,-89,-72,-53,-34,-15,1,16,29,39,46,50,51,50,48,43,37,30,22,3,5,6,7,8,9,10,11,12,12,12,11,10,8,6,4,1,1,4,6,8,10,11,12,12,12,11,10,9,8,7,6,5,3,1,8,11,12,13,14,13,11,8,4,1,3,6,9,12,15,18,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,16,12,8,6,8,11,14,17,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,13,5,1,3,6,9,12,14,13,12,11,8,6
